### ISSUE TITLE
Extra board gets added when clicked on the existing board.

### ISSUE THREAD

**Issue by Aswal-Ashutosh** [untitled-team-101/Whiteboard#7] opened 2021-10-03 13:34 UTC
When clicking on the first board which has been added to the multi-page bar an extra board gets created.

![bug](https://user-images.githubusercontent.com/60442620/135755902-3b462ac8-7cc9-48df-8d2f-6d09aabdf70d.gif)

**Comment by Yugal41735** [comment] 2021-10-03 13:40
hello, I have absolutely no knowledge regarding html,css and javascript but i am willing to learn and then contribute so if its possible do tell me. Thank u

**Comment by Simetraa** [comment] 2021-10-03 14:06
This seems to be related to this section, namely the addBoard() call. 
```js
function prevBoard() {
    if (currentIndex === 0) {
        window.alert("ANDHE PEECHE KOI BOARD NAHI HAI !!")
    } else {
        if (currentIndex === boardStore.length) {
            let temp = [save.undo_list, save.redo_list];
            addBoard()
            save.undo_list = temp[0]
            save.redo_list = temp[1]
            currentIndex -= 1
        } else {
            boardStore[currentIndex].board = canvas.toDataURL()
        }
        saveHistory();
        currentIndex -= 1
        let previousState = boardStore[currentIndex].board
        let currImg = document.createElement('img')
        currImg.src = previousState
        currImg.onload = function() {
            ctx.clearRect(0, 0, canvas.width, canvas.height)
            ctx.drawImage(currImg, 0, 0)
            checkBoardRequest()
        }
        loadHistory();
    }
    showPreview();
}
```

**Comment by grawish** [comment] 2021-10-03 14:22
> This seems to be related to this section, namely the addBoard() call.
> 
> ```js
> function prevBoard() {
>     if (currentIndex === 0) {
>         window.alert("ANDHE PEECHE KOI BOARD NAHI HAI !!")
>     } else {
>         if (currentIndex === boardStore.length) {
>             let temp = [save.undo_list, save.redo_list];
>             addBoard()
>             save.undo_list = temp[0]
>             save.redo_list = temp[1]
>             currentIndex -= 1
>         } else {
>             boardStore[currentIndex].board = canvas.toDataURL()
>         }
>         saveHistory();
>         currentIndex -= 1
>         let previousState = boardStore[currentIndex].board
>         let currImg = document.createElement('img')
>         currImg.src = previousState
>         currImg.onload = function() {
>             ctx.clearRect(0, 0, canvas.width, canvas.height)
>             ctx.drawImage(currImg, 0, 0)
>             checkBoardRequest()
>         }
>         loadHistory();
>     }
>     showPreview();
> }
> ```

so can you fix that issue?

**Comment by Simetraa** [comment] 2021-10-03 14:26
> > This seems to be related to this section, namely the addBoard() call.
> > ```js
> > function prevBoard() {
> >     if (currentIndex === 0) {
> >         window.alert("ANDHE PEECHE KOI BOARD NAHI HAI !!")
> >     } else {
> >         if (currentIndex === boardStore.length) {
> >             let temp = [save.undo_list, save.redo_list];
> >             addBoard()
> >             save.undo_list = temp[0]
> >             save.redo_list = temp[1]
> >             currentIndex -= 1
> >         } else {
> >             boardStore[currentIndex].board = canvas.toDataURL()
> >         }
> >         saveHistory();
> >         currentIndex -= 1
> >         let previousState = boardStore[currentIndex].board
> >         let currImg = document.createElement('img')
> >         currImg.src = previousState
> >         currImg.onload = function() {
> >             ctx.clearRect(0, 0, canvas.width, canvas.height)
> >             ctx.drawImage(currImg, 0, 0)
> >             checkBoardRequest()
> >         }
> >         loadHistory();
> >     }
> >     showPreview();
> > }
> > ```
> 
> so can you fix that issue?

Yep, it'll take me a bit to read through the codebase but once that's done I'll fix it.

**Comment by Aswal-Ashutosh** [comment] 2021-10-03 14:27
Empty multipage bar, in the beginning, is not making any sense. 
It should be containing the default board which has been provided to the users.

**Comment by Simetraa** [comment] 2021-10-03 14:35
> Empty multipage bar, in the beginning, is not making any sense. It should be containing the default board which has been provided to the users.

Yeah, it doesn't make much sense not to have a default board; given there's no way to delete/remove boards.

**Comment by Ayan-Dhara** [comment] 2021-10-03 15:50
Actually no extra board created. 
The actual issue is at the beginning the is a **single board, but not shown** on the multi-board bar.
So when new board is added and **clicked on another board from the multi-board bar, the list gets refreshed and become visible**.

**Comment by Aswal-Ashutosh** [comment] 2021-10-03 16:54
> Actually no extra board created. The actual issue is at the beginning the is a **single board, but not shown** on the multi-board bar. So when new board is added and **clicked on another board from the multi-board bar, the list gets refreshed and become visible**.

@Ayan-Dhara I debugged the code. And found that the **addBoard** function gets called 2 times one from that the add button and the next one is by clicking on that mini board which invokes the **prevBoard** function.

I am currently trying to fix this issue and optimize **showPreview** function which is doing unnecessary work by creating all the thumbnails again instead of creating the new one only.

**Comment by Ayan-Dhara** [comment] 2021-10-03 17:36
OK, Go on. But the issue is still not assigned to you.

**Comment by Aswal-Ashutosh** [comment] 2021-10-03 17:55
> OK, Go on. But the issue is still not assigned to you.

You can assign it to me. I have almost fixed it.

**Closed** 2021-10-03 20:46 UTC
Labels: bug, hacktoberfest
